### ISSUE TITLE
make user hoverable tooltip

### ISSUE THREAD

**Issue by sarisia** [aria-music/zundacord#28]
![image](https://user-images.githubusercontent.com/33576079/232120141-b0110908-205f-46b9-8f55-87a819606087.png)

**Comment by mnsinri** [comment]
resolve https://github.com/aria-music/zundacord/issues/28
<img width="385" alt="image" src="https://user-images.githubusercontent.com/44370583/236678780-e81dace5-4058-4b84-9885-04faeee7028e.png">
